### ISSUE TITLE
`hyperspy` is not compatible with 3.12

### ISSUE THREAD

**Issue by TLCFEM** [FAIRmat-NFDI/pynxtools-em#71]
`hyperspy==1.7.5` cannot be compiled in 3.12.

`hyperspy==1.7.6` can be compiled in 3.12.

Currently CI installs 1.7.6 thus it did not report the error.

https://github.com/FAIRmat-NFDI/pynxtools-em/actions/runs/10820193110/job/30019719062#step:5:64

But the downstream resolver may pick an old version that may cause error.

It's thus better to constrain the version `hyperspy>1.7.5`.

**Comment by mkuehbach** [comment]
Closed, as not a direct bug on pynxtools-em side, handled by #80 which is a temporary fix until solved on the hyperspy
